language: android
android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
  
    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-18